apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80            # External port exposed via LoadBalancer
      targetPort: 80      # Your frontend (Nginx) container runs on port 80
  type: LoadBalancer
